# hugo.toml - 中文主页，支持多语言扩展

baseURL = "https://evan-manual.com/"
languageCode = "zh-CN"
defaultContentLanguage = "zh"
title = "伊万的个人主页"
theme = "anatole"

summaryLength = 10
enableEmoji = true
enableRobotsTXT = true

# 语法高亮
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

# Localized dates requires Hugo version 0.87.0
localizedDates = false

[module]
[[module.imports]]
path = "github.com/hugomods/icons"

[permalinks]
post = "/post/:slug/"

# [params] 主题自定义参数
[params]
mermaidEnable = true
profilePicture = "images/profile.png"
favicon = "favicons/"   # 注意路径只到文件夹，不带文件名
customCSS = ["css/custom.css"]


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[related]
  includeNewer = true
  threshold = 80
  toLower = true
[[related.indices]]
  name = "keywords"
  weight = 100
[[related.indices]]
  name = "tags"
  weight = 80

[services]
# Enable Disqus.Disqus.Shortname
  [services.disqus]
    #shortname = 'your-disqus-shortname'
# Google Analytics
  [services.googleAnalytics]
    #ID = 'G-MEASUREMENT_ID'