baseURL = 'https://evan-manual.com/'
languageCode = 'zh-CN'
defaultContentLanguage = "zh"
title = '伊万的个人主页'
theme = 'anatole'

[params]
profilePicture = "images/profile.png"
favicon = "favicons/"   # 注意路径只到文件夹，不带文件名