# wrangler.toml
name = 'evanmanual'
compatibility_date = "2025-10-26"

routes = [
  { pattern = "evan-manual.com/*", zone_name = "evan-manual.com" }
]

[build]
command = "chmod a+x build.sh && ./build.sh"

[assets]
directory = "./public"
not_found_handling = "404-page"
